import React from 'react'
import "./Vazifalar"
import { Container } from './Vazifalar'
const Vazifalar = () => {
  return (
    <Container>
        <h2 id='vazifa'>Marketing xizmatlari bo‘limining vazifalari:</h2>
        <p>Ta’lim xizmatlari bozorida marketing tadqiqotlarini uzluksiz amalga oshirib, ta’lim xizmatlariga qo‘yilgan, ya’ni bakalavriat yo‘nalishlari va magistratura mutaxassisliklari bo‘yicha bitiruvchilarning kasbiy mahoratini (malakaviy sifatlarini) o‘rganish hamda ularning ish beruvchilar (iste’molchilar) talablariga muvofiqligini aniqlash.
Respublika iqtisodiyoti va ijtimoiy soha tarmoqlarida bakalavriat yo‘nalishlari va magistratura mutaxassisliklari bo‘yicha raqobatli ta’lim xizmatlarining paydo bo‘lishiga olib kelishi mumkin bo‘lgan xizmatlar bozori kon’yukturasining o‘zgarishini taxlil qilish hamda yangicha rivojlanish yo‘nalishlarini belgilash.
Bakalavriat yo‘nalishlari va magistratura mutaxassisliklari bo‘yicha ta’lim xizmatlari bozori va kon’yukturasiga ta’sir ko‘rsatuvchi turli xil omillar (segmentlar) o‘rtasidagi o‘zaro aloqalarni taxlil qilish asosida bitiruvchilarni oldindan ishga taqsimlash tizimini tashkil qilish va amalga oshirish.
Bakalavriat yo‘nalishlari va magistratura mutaxassisliklari bo‘yicha bitiruvchilarga talab va takliflar nisbatini o‘z ichiga olgan holda ishga taqsimlash obyektlari–ta’lim xizmatlari iste’molchilari (ish beruvchi korxonalar, turli mulkchilik shakliga ega bo‘lgan tashkilotlar – davlat va maxalliy boshqaruv organlari, davlat va nodavlat tashkilotlari va x.k.) tuzilmasini baholash, geografik joylashishini aniqlash va guruhlash, potentsial imkoniyatlarini tashxis qilish orqali to‘liq ma’lumotlar bankini yaratish.
Joriy yil bitiruvchilari haqida (ta’lim yo‘nalishlari va mutaxassisliklar kesimida davlat granti va to‘lov-shartnoma asosida kunduzgi va maxsus sirtqi ta’lim shakllari bo‘yicha familiyasi, ismi-sharifi ko‘rsatilgan holda) ma’lumotlar bankini yaratish.
Respublika va tegishli xududlar (viloyatlar) iqtisodiyoti hamda ijtimoiy soha tarmoqlarining rivojlanish istiqbollarini hisobga olgan holda yangi ta’lim yo‘nalishlari yoki mutaxassisliklarini ochish, shuningdek ta’lim xizmatlari bozori talablariga javob bermaydiganlarini to‘xtatish bo‘yicha takliflar tayyorlash, yetarlicha ish beruvchiga ega bo‘lmagan bakalavriat yo‘nalishlari va magistratura mutaxassisliklari ro‘yxatini aniqlash.
Talabalar qabuli ko‘rsatkichlarini aniqlash maqsadida ish beruvchilar (korxona va tashkilotlar)ning mavjud ta’lim (tayyorlov) yo‘nalishlari yoki mutaxassisliklarga bo‘lgan talablari (buyurtmalari)ni hisobga olgan xolda davlat grantlari va to‘lov-kontrakt bo‘yicha joriy va istiqbolli «buyurtmalar portfeli»ni shakllantirish.
Toshkent davlat transport universiteti bitiruvchilarini ishga taqsimlash bo‘yicha komissiyasini tashkil etish, taqsimot komissiyasi tomonidan ish beruvchi muassasa, korxona va tashkilotlarning kadrlarga bo‘lgan real extiyojlariga muvofiq bitiruvchilarni ishga taqsimlash rejalarini (dastlabki, aniqlashgan) ishlab chiqish va yakuniy taqsimotni o‘tkazib, uning natijalari bo‘yicha bitiruvchilar shaxsiy taqsimot qaydnomasini tuzish xamda umumlashtirish.
TDTrU bitiruvchilarini ishga taqsimlash bo‘yicha komissiyasi faoliyati uchun zarur bo‘lgan bakalavriat yo‘nalishlari va magistratura mutaxassisliklari bo‘yicha har bir bitiruvchining reytingi va malakaviy sifatlari to‘g‘risida tavsifnoma, bitiruvchilarning qaysi muassasa, tashkilot yoki korxonada ishlashini xoxlashiga oid anketa so‘rovlari natijalari va ish beruvchilar (iste’molchilar)dan korxona yoki tashkilotdagi mavjud mehnat hamda maishiy-madaniy shart-sharoitlar, ish haqi miqdorlari haqidagi ma’lumotlarni tayyorlash.
Bitiruvchilarni ishga taqsimlash va ularning  joylashishiga oid  barcha zaruriy xujjatlarni (diplomdan ko‘chirma, ishga yuborilganlik to‘g‘risida yo‘llanma, taqsimot komissiyasi qarori, shaxsiy taqsimot qaydnomasi) tayyorlash, rasmiylashtirish va bitiruvchilarga topshirish.
Taqsimot komissiyasi tomonidan ishga taqsimlangan yosh mutaxassislardan tushgan arizalarini ko‘rib chiqish va yechim qabul qilish, zarur va asoslangan xollarda qayta taqsimlash yoki mustaqil ishga joylashish jarayonini amalga oshirish uchun universitet komissiyasiga murojaat etish.
Ishga taqsimlangan va joylashgan bitiruvchilarning korxonalar va tashkilotlar kesimida ishga joylashuvi haqida to‘liq yakuniy ma’lumotlar bankini yaratish.
Bitiruv malakaviy ishlari va magistrlik dissertatsiyalariga rahbarlik hamda davlat unitary korxonalari(DUK) tarkibiga ish beruvchi (buyurtmachi) korxona va tashkilotlarning yuqori malakali mutaxassislarini jalb etish.
Ish beruvchi korxona va tashkilotlar bilan kadrlar tayyorlash, ularni ishga joylashtirish, o‘quv-ilmiy-ishlab chiqarish markazlari (poligonlari, amaliyot bazalari) tashkil etish bo‘yicha asosnoma va takliflar tayyorlash hamda moddiy-texnik xamkorlikka oid shartnomalar tuzish, shuningdek ular bilan qata aloqalarni o‘rnatish.
Joriy yilda va o‘tgan yillar davomida ishga joylashgan yosh mutaxassislar bilan qayta aloqalar o‘rnatish, zaruriy hollarda ularga amaliy-uslubiy yordamlar ko‘rsatish, maslaxatlar berish hamda mexnat faoliyati natijalarini umumlashtirish.
Yangi o‘quv yili qabul rejasining bajarilishi (davlat grantlari va to‘lov-kontrakt bo‘yicha qabul rejasi, tushgan arizalar, konkurs, qabul qilingan talabalar soni, ularning kurslar, ta’lim yo‘nalishlari (mutaxassisliklar) bo‘yicha taqsimlanishi, o‘qitish tillari va x.k.) haqida ma’lumotlar bankini yaratish.
Yangi o‘quv yilida davlat grantlari asosida qabul qilingan talabalar bilan universitet o‘rtasida o‘qishni tugatgandan so‘ng ishga taqsimlangan joyida 3 yil ishlab berishi to‘g‘risida ikki tomonlama shartnomalar tuzish.
Talabalarning ishlab chiqarish va diplom oldi amaliyoti bazalarini aniqlash maqsadida korxonalar, tashkilotlar va xususiy xo‘jaliklar bilan aloqalar o‘rnatish hamda shartnomalar tuzish, ish beruvchilar (iste’molchilar)ning bitiruvchilar haqidagi fikrlari (e’tirozlari, yosh mutaxassisning kamchiliklari, rad qilinishi sabablari) va ta’lim sifatini oshirishga oid takliflari asosida amaldagi ta’lim mazmuniga muayyan o‘zgartirishlar kiritish bo‘yicha tavsiyalar tayyorlash.
Bakalavriat yo‘nalishlari va magistratura mutaxassisliklari bo‘yicha talabalarning kasbiy maxoratini oshirish va bitiruvchilarni ishga taqsimlash borasida oliy ta’lim muassasasining tegishli bo‘linmalari (turli ilmiy-uslubiy kengashlar, ilmiy, o‘quv-uslubiy bo‘linmalar, fakultetlar, kafedralar va x.k.) bilan xamkorlik qilish, ular tomonidan amalga oshirilgan chora-tadbirlar samaradorligini taxlil qilish va baxolashda ishtirok etish, umumiy marketing siyosatini amalga oshirishda barcha tegishli bo‘linmalar faoliyatini muvofiqlashtirish.
Ta’lim xizmatlari xalqaro bozori bo‘yicha marketing izlanishlarini olib borish va taxliliy xulosalar tayyorlash.
Ish beruvchilar (iste’molchilar)ga axborotlar vositasida ta’sir ko‘rsatish yo‘llarini tanlash, ommaviy axborot vositalari (gazetalar, jurnallar, radio-televidenie, elektron aloqa, veb-sayt) orqali bitiruvchilar to‘grisida (viloyatlar bo‘yicha ta’lim yo‘nalishlari, mutaxassisliklar kesimida) ma’lumotlar e’lon qilinishini, oliy ta’lim muassasasi veb-saytida joylashtirilishini, ma’lumotnomalar nashr qilish va ularning iste’molchilar (ish beruvchilar)ga yetqazilishini ta’minlash, reklamalar mazmuni, reklama modullarining xomaki nusxalari, maqolalar matnlari, video va audiotasmalar  stsenariylarini tayyorlashda ishtirok etish.
Yuqori (bitiruvchi) kurslar talabalarida kasbiy maxorat sifatlarining bakalavr (magistr) ma’lumot darajasiga va ish beruvchilar (iste’molchilar) talablariga muvofiq shakllanishi jarayonini o‘rganish, taxlil qilish xamda marketing izlanishlari natijalari taxlilidan kelib chiqqan xolda raqobatbardosh bitiruvchi shaxsini shakllantirish maqsadida fakultetlar, tegishli kafedralar va ilmiy, o‘quv-metodik bo‘limlarga buyurtmachilar (iste’molchilar) tavsiyalarini taqdim etish.
Turdosh oliy ta’lim muassasalarida bakalavriat yo‘nalishlari va magistratura mutaxassisliklari bo‘yicha tayyorlanayotgan raqobatli bitiruvchilarning kasbiy maxorati darajasi, ularning ustunligi va kamchiligini baxolash xamda o‘z bitiruvchilari bilan taqqoslash.
Universitetda magistr darajali ilmiy-pedagogik kadrlarga bo‘lgan extiyojni aniqlash va Oliy va o‘rta maxsus ta’lim vazirligining bitiruvchilarni ishga taqsimlash va yosh mutaxassislar faoliyatining monitoringini olib borish ishlarini muvofiqlashtiruvchi maxsus komissiyasiga taqdim etish.
Kadrlarga bo‘lgan real extiyojlar va bitiruvchilarni yakuniy ishga taqsimlash natijalari xaqidagi ma’lumotlarni taalluqli vazirlik (idora)ning maxsus komissiyasi xamda ish beruvchi muassasa, korxona va tashkilotlarga davriy ravishda taqdim etish, ishga taqsimlash jarayoni nazorat rejasining bajarilishi bo‘yicha Oliy va o‘rta maxsus ta’lim vazirligiga axborotlar taqdim etish.
Fan-texnika yutuqlarini hisobga olgan xolda xamda bakalavr va magistr bitiruvchilarning kasbiy maxorati (malakaviy sifatlari)ni yaxshilash maqsadida raqobatbardosh bo‘lgusi mutaxassis shaxsini takomillashtirish bo‘yicha taklif va tavsiyalar ishlab chiqish.
Bakalavriat yo‘nalishlari va magistratura mutaxassisliklari bo‘yicha bitiruvchilarni ishga taqsimlashda yordamchi-vositachilik tuzilmalarini tanlash (xokimiyatlar, mexnat va axolini ijtimoiy ximoya qilish boshqarmalari (bo‘limlari), savdo-sanoat palatasi, agentliklar, ishonchli vakillar va x.k.) va ularning imkoniyatlaridan samarali foydalanish.
Bakalavriat yo‘nalishlari va magistratura mutaxassisliklari bo‘yicha bitiruvchilarning imkoniyatlari va ustunliklarini namoyish qilish maqsadida universitetning respublika, mintaqaviy va xalqaro ko‘rgazmalar, yarmarkalarda ishtirok etishini ta’minlash, muassasa xududida ko‘rgazma va vitrinali ekspozitsiyalar tashkil etish.
Imzolangan shartnomalarga muvofiq ish beruvchilarni  belgilangan muddatlarda bitiruvchilar bilan ta’minlash maqsadida oliy ta’lim muassasasining barcha tegishli bo‘linmalari bilan talabalar qabuli va bitiruvchilarni ishga taqsimlash rejalarini muvofiqlashtirish.
Universitetning tegishli bo‘linmalari (kengashlar, fakultetlar, kafedralar va x.k.) bilan xamkorlikda bakalavriat yo‘nalishlari va magistratura mutaxassisliklarini davlat granti asosida bitiruvchilarning uch yil kafolatli ishlashi, shuningdek uch yillik majburiy ishlab berish shartini o‘tayotgan yosh mutaxassislarning kasbiy faoliyati, saviyasini oshirish borasidagi ishlar va ularning xizmat pog‘onalaridan ko‘tarilishiga ko‘maklashish yuzasidan chora-tadbirlar ishlab chiqish va amalga oshirish.
Bakalavriat yo‘nalishlari va magistratura mutaxassisliklari bo‘yicha bitiruvchilarni ishga taqsimlash va joylashtirish, yosh mutaxassislarning mexnat faoliyati natijalari bo‘yicha oliy ta’lim muassasasining ichki hisobotini yuritish va tashkil etish, marketing, monitoring va bitiruvchilarni ishga joylashtirish bo‘limining yillik hisobotini tayyorlash.</p>

    </Container>
  )
}

export default Vazifalar
